name: Skills Assessment Autograder

on: push

jobs:
  autograde_assessment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint
      - name: Evaluate code style
        run: |
          pylint **/*.py --output-format=colorized --confidence=HIGH --good-names-rgxs=^[A-Za-z]$ || exit 0
      - name: Run tests
        uses: education/autograding@v1